<a href="https://colab.research.google.com/github/Manojkumar310897/Task-8/blob/main/NLP_Translation_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install deep-translator

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: deep-translator in /usr/local/lib/python3.8/dist-packages (1.10.0)
Requirement already satisfied: pypdf[pdf]<4.0.0,>=3.3.0 in /usr/local/lib/python3.8/dist-packages (from deep-translator) (3.4.1)
Requirement already satisfied: docx2txt[docx]<0.9,>=0.8 in /usr/local/lib/python3.8/dist-packages (from deep-translator) (0.8)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.9.1 in /usr/local/lib/python3.8/dist-packages (from deep-translator) (4.11.2)
Requirement already satisfied: requests<3.0.0,>=2.23.0 in /usr/local/lib/python3.8/dist-packages (from deep-translator) (2.28.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4<5.0.0,>=4.9.1->deep-translator) (2.4)
WARNING: docx2txt 0.8 does not provide the extra 'docx'
WARNING: pypdf 3.4.1 does not provide the extra 'pdf'
Requirement already satisfied: typing_extensions>=3.10.0.0 in /usr/local/lib/python3.8/dist-packages (from pypdf[pdf]<4.0.0,>=3.3.0->deep-translator) (4.4.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests<3.0.0,>=2.23.0->deep-translator) (1.24.3)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df=pd.read_csv("/content/drive/MyDrive/Colab Notebooks/English.csv")

In [ ]:
df.head(100)

   English words/sentences
0                      Hi.
1                     Run!
2                     Run!
3                     Who?
4                     Wow!
..                     ...
95                Call us.
96                Call us.
97                Come in.
98                Come in.
99                Come in.

[100 rows x 1 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175621 entries, 0 to 175620
Data columns (total 1 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   English words/sentences  175621 non-null  object
dtypes: object(1)
memory usage: 1.3+ MB

In [ ]:
# It takes so much time for translating the entire dataset,so we are taking only first 100 words or sentences.
df1=df.head(100)
df1

   English words/sentences
0                      Hi.
1                     Run!
2                     Run!
3                     Who?
4                     Wow!
..                     ...
95                Call us.
96                Call us.
97                Come in.
98                Come in.
99                Come in.

[100 rows x 1 columns]

In [ ]:
from deep_translator import GoogleTranslator
german =[]
for i in df1['English words/sentences']:
      a = GoogleTranslator(source='auto', target='de').translate(i)
      german.append(''.join(a))

In [ ]:
ge =pd.Series(german)
ger=pd.DataFrame(ge, columns=["german words"])
ger.head(10)

  german words
0       Hallo.
1      Laufen!
2      Laufen!
3         WHO?
4         Wow!
5       Feuer!
6       Hilfe!
7    Springen.
8     Stoppen!
9     Stoppen!

In [ ]:
spanish =[]
for j in df1['English words/sentences']:
  b = GoogleTranslator(source='auto', target='spanish').translate(j)
  spanish.append(''.join(b))

In [ ]:
sp =pd.Series(spanish)
spa=pd.DataFrame(sp, columns=["spanish words"])
spa.head(10)

  spanish words
0         Hola.
1      Â¡Correr!
2      Â¡Correr!
3         Â¿OMS?
4        Â¡Guau!
5       Â¡Fuego!
6       Â¡Ayuda!
7       Saltar.
8     Â¡Detener!
9     Â¡Detener!

In [ ]:
french =[]
for k in df1['English words/sentences']:
  c = GoogleTranslator(source='auto', target='french').translate(k)
  french.append(''.join(c))

In [ ]:
fe =pd.Series(french)
fer=pd.DataFrame(fe, columns=["french words"])
fer.head(10)

  french words
0       Salut.
1      Courir!
2      Courir!
3         OMS?
4        Ouah!
5         Feu!
6       Aider!
7        Saut.
8       ArrÃªt!
9       ArrÃªt!

In [ ]:
different_lan = pd.concat([df1,ger,spa,fer],axis=1)
different_lan.head(10)

  English words/sentences german words spanish words french words
0                     Hi.       Hallo.         Hola.       Salut.
1                    Run!      Laufen!      Â¡Correr!      Courir!
2                    Run!      Laufen!      Â¡Correr!      Courir!
3                    Who?         WHO?         Â¿OMS?         OMS?
4                    Wow!         Wow!        Â¡Guau!        Ouah!
5                   Fire!       Feuer!       Â¡Fuego!         Feu!
6                   Help!       Hilfe!       Â¡Ayuda!       Aider!
7                   Jump.    Springen.       Saltar.        Saut.
8                   Stop!     Stoppen!     Â¡Detener!       ArrÃªt!
9                   Stop!     Stoppen!     Â¡Detener!       ArrÃªt!